name: Bump version

on:
    push:
        branches:
            - main

jobs:
    releaseJob:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout main branch to calculate changelog
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Calculate version
              id: tag_version
              uses: miguelfito/github-bump-and-tag-action@v1
              with:
                  github_token: ${{ secrets.Token }}
                  default_bump: patch
                  create_annotated_tag: true
                  tag_prefix: v
                  dry_run: false

            - name: Get updated commit SHA
              run: |
                  echo "##[set-output name=commit_id;]$(git rev-parse HEAD)"
              id: updated_sha

            - name: Bump version and push tag
              uses: miguelfito/github-bump-and-tag-action@v1
              with:
                  github_token: ${{ secrets.Token }}
                  commit_sha: ${{ steps.updated_sha.outputs.commit_id }}
                  default_bump: patch
                  create_annotated_tag: true
                  tag_prefix: v

