name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Bump version and create tag
        id: tag_version
        uses: miguelfito/github-bump-and-tag-action@v1
        with:
          github_token: ${{ secrets.Token }}
          default_bump: false
          create_annotated_tag: true
          tag_prefix: v
          dry_run: true
  
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.Token }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
